apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-docker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-docker-app
  template:
    metadata:
      labels:
        app: my-docker-app
    spec:
      containers:
      - name: my-docker-container
        image: my_docker_project:latest
        imagePullPolicy: Never   # <-- Prevent Kubernetes from pulling remotely
        ports:
        - containerPort: 80

